name: Mise à jour quotidienne

on:
  schedule:
    - cron: '0 10 * * *'  # tous les jours à 10h UTC
  workflow_dispatch:  # permet de lancer manuellement si besoin

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        pip install -r requirements.txt

    - name: Exécuter le script de mise à jour
      run: |
        python3 daily_update.py
